<?php
// $Id$

/**
 * @file
 * Provides parsing ability from sql strings into Drupal DBTNG objects.
 */

/**
 * Implements hook_menu().
 */
function sql_parser_menu() {
  $items['admin/config/development/sql-parser'] = array(
    'title' => 'SQL Parser',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sql_parser_parser_form'),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Page Callback.
 */
function sql_parser_parser_form($form, &$form_state) {
  if ($form_state['post']['sql']) {
    $parsed_sql = sql_parser_parse($form_state['post']['sql']);
    $query_string = sql_parser_convert($parsed_sql);
  }
  $form['sql'] = array(
    '#title' => 'Original SQL String',
    '#type' => 'textarea',
    '#default_value' => $form_state['post']['sql'],
  );
  $form['output'] = array(
    '#title' => 'Database Object',
    '#type' => 'textarea',
    '#rows' => 10,
    '#attributes' => array(
      'readonly' => 'readonly',
    ),
    '#value' => $query_string,
  );
  $form['submit'] = array(
    '#type' => 'button',
    '#value' => t('Convert'),
  );
  return $form;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function sql_parser_parse($sql) {
  module_load_include('inc', 'sql_parser', 'includes/sql_dialect');
  module_load_include('inc', 'sql_parser', 'includes/sql_lexer');
  module_load_include('inc', 'sql_parser', 'includes/sql_parser');
  module_load_include('inc', 'sql_parser', 'includes/sql_object');

  $parser = new SqlParser($sql);
  return $parser->parse();
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function sql_parser_convert($parsed_sql) {
  module_load_include('inc', 'sql_parser', 'includes/sql_converter');

  $converter = new SqlDBTNGConverter($parsed_sql);
  return $converter->convert();
}
